/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import FGUI_PGamePause from "./FGUI_PGamePause";
import FGUI_EnterGameLoadingCom from "./FGUI_EnterGameLoadingCom";
import FGUI_AniCom from "./FGUI_AniCom";
import FGUI_ComTips from "./FGUI_ComTips";
import FGUI_BoosHp_Bar from "./FGUI_BoosHp_Bar";
import FGUI_passCardUItem from "./FGUI_passCardUItem";
import FGUI_VirtualRocker from "./FGUI_VirtualRocker";
import FGUI_yellowkuang from "./FGUI_yellowkuang";
import FGUI_homeMidItem from "./FGUI_homeMidItem";
import FGUI_homeTabCom from "./FGUI_homeTabCom";
import FGUI_PGameCustomsLoading from "./FGUI_PGameCustomsLoading";
import FGUI_ShareCom from "./FGUI_ShareCom";
import FGUI_nativeCom from "./FGUI_nativeCom";
import FGUI_GameFitingPlan from "./FGUI_GameFitingPlan";
import FGUI_rotatingRay from "./FGUI_rotatingRay";
import FGUI_playerItem from "./FGUI_playerItem";
import FGUI_playerCom from "./FGUI_playerCom";
import FGUI_ConfirmBuy from "./FGUI_ConfirmBuy";
import FGUI_RoleAdvancedView from "./FGUI_RoleAdvancedView";
import FGUI_PropItem from "./FGUI_PropItem";
import FGUI_PGameActive from "./FGUI_PGameActive";
import FGUI_Component16 from "./FGUI_Component16";
import FGUI_ActiveItem from "./FGUI_ActiveItem";
import FGUI_ActiveTopCom from "./FGUI_ActiveTopCom";
import FGUI_DesBtnp from "./FGUI_DesBtnp";
import FGUI_BlockComp from "./FGUI_BlockComp";
import FGUI_PGetCard from "./FGUI_PGetCard";
import FGUI_getCardCom from "./FGUI_getCardCom";
import FGUI_getCardBoardCom from "./FGUI_getCardBoardCom";
import FGUI_PConfirm from "./FGUI_PConfirm";
import FGUI_confirmBoardCom from "./FGUI_confirmBoardCom";
import FGUI_PGameLoading from "./FGUI_PGameLoading";
import FGUI_PGamePlay from "./FGUI_PGamePlay";
import FGUI_PGameStart from "./FGUI_PGameStart";
import FGUI_FreeReward from "./FGUI_FreeReward";
import FGUI_FreeRewardItem from "./FGUI_FreeRewardItem";
import FGUI_FreeRewardBtn from "./FGUI_FreeRewardBtn";
import FGUI_ModeTipsPlan from "./FGUI_ModeTipsPlan";
import FGUI_SelectMode from "./FGUI_SelectMode";
import FGUI_ModeTips from "./FGUI_ModeTips";
import FGUI_SelectModeItemPlan from "./FGUI_SelectModeItemPlan";
import FGUI_GameOverPlan from "./FGUI_GameOverPlan";
import FGUI_UniversalEndPlan from "./FGUI_UniversalEndPlan";
import FGUI_UniversalTwoEndPlan from "./FGUI_UniversalTwoEndPlan";
import FGUI_OverEndTaskPlan from "./FGUI_OverEndTaskPlan";
import FGUI_EndTaskBar from "./FGUI_EndTaskBar";
import FGUI_EnemyIconPlan from "./FGUI_EnemyIconPlan";
import FGUI_GameView from "./FGUI_GameView";
import FGUI_ExistentCom from "./FGUI_ExistentCom";
import FGUI_bloom from "./FGUI_bloom";
import FGUI_ButItemOne from "./FGUI_ButItemOne";
import FGUI_waveRewrds from "./FGUI_waveRewrds";
import FGUI_UnLockSkin from "./FGUI_UnLockSkin";
import FGUI_RoleView from "./FGUI_RoleView";
import FGUI_RoleItem from "./FGUI_RoleItem";
import FGUI_PropertyItem from "./FGUI_PropertyItem";
import FGUI_SkillItem from "./FGUI_SkillItem";
import FGUI_RoleHeadItem from "./FGUI_RoleHeadItem";
import FGUI_MysteriousRewards from "./FGUI_MysteriousRewards";
import FGUI_StartView from "./FGUI_StartView";
import FGUI_BeginButton from "./FGUI_BeginButton";
import FGUI_EnemyHp_Bar from "./FGUI_EnemyHp_Bar";
import FGUI_RoleHp_Bar from "./FGUI_RoleHp_Bar";
import FGUI_PGameEnd from "./FGUI_PGameEnd";
import FGUI_RoundHalfImg from "./FGUI_RoundHalfImg";
import FGUI_LightBox from "./FGUI_LightBox";
import FGUI_D_refreshDiamond from "./FGUI_D_refreshDiamond";
import FGUI_D_refreshGold from "./FGUI_D_refreshGold";
import FGUI_GameShopIn from "./FGUI_GameShopIn";
import FGUI_GameOverRole from "./FGUI_GameOverRole";
import FGUI_BUFFShow from "./FGUI_BUFFShow";
import FGUI_BUFFSelect from "./FGUI_BUFFSelect";
import FGUI_SkillSelect from "./FGUI_SkillSelect";
import FGUI_BUFFInfo from "./FGUI_BUFFInfo";
import FGUI_AttackTxT from "./FGUI_AttackTxT";
import FGUI_ExpTxT from "./FGUI_ExpTxT";
import FGUI_DiamontemComp from "./FGUI_DiamontemComp";
import FGUI_CommodityComp from "./FGUI_CommodityComp";
import FGUI_DiamonItemBtn from "./FGUI_DiamonItemBtn";
import FGUI_GoldComp from "./FGUI_GoldComp";
import FGUI_goldItem from "./FGUI_goldItem";
import FGUI_PGameHome from "./FGUI_PGameHome";
import FGUI_PGameHunter from "./FGUI_PGameHunter";
import FGUI_TopItem from "./FGUI_TopItem";
import FGUI_UnblockSkinBtnp from "./FGUI_UnblockSkinBtnp";
import FGUI_foreverItem from "./FGUI_foreverItem";
import FGUI_HunterItem from "./FGUI_HunterItem";
import FGUI_Elf_Item_pro from "./FGUI_Elf_Item_pro";
import FGUI_GoldTicket from "./FGUI_GoldTicket";
import FGUI_SilverTicket from "./FGUI_SilverTicket";
import FGUI_TicketLight from "./FGUI_TicketLight";
import FGUI_GetRewardBtn from "./FGUI_GetRewardBtn";
import FGUI_PassCardListCom from "./FGUI_PassCardListCom";
import FGUI_passCardFreeItem from "./FGUI_passCardFreeItem";
import FGUI_SilverTicket1 from "./FGUI_SilverTicket1";
import FGUI_CoTips from "./FGUI_CoTips";
import FGUI_levelProgressBar from "./FGUI_levelProgressBar";
import FGUI_experienceBarCom from "./FGUI_experienceBarCom";
import FGUI_timeCom from "./FGUI_timeCom";
import FGUI_deadMsgCom from "./FGUI_deadMsgCom";
import FGUI_hpBar from "./FGUI_hpBar";
import FGUI_playerHp from "./FGUI_playerHp";
import FGUI_SkillCom from "./FGUI_SkillCom";
import FGUI_chooseSkillCom from "./FGUI_chooseSkillCom";
import FGUI_PHuntTask from "./FGUI_PHuntTask";
import FGUI_taskProcessingCom from "./FGUI_taskProcessingCom";
import FGUI_rewardCom from "./FGUI_rewardCom";
import FGUI_taskItemCom from "./FGUI_taskItemCom";
import FGUI_taskBtn from "./FGUI_taskBtn";
import FGUI_taskBtnFinishedCout from "./FGUI_taskBtnFinishedCout";
import FGUI_huntTaskBoard from "./FGUI_huntTaskBoard";
import FGUI_adItem from "./FGUI_adItem";
import FGUI_adProgressBar from "./FGUI_adProgressBar";
import FGUI_GoonGame from "./FGUI_GoonGame";
import FGUI_LifeTime30 from "./FGUI_LifeTime30";
import FGUI_Ray from "./FGUI_Ray";
import FGUI_SetCom from "./FGUI_SetCom";
import FGUI_HuntBtn from "./FGUI_HuntBtn";
import FGUI_SelectModePlan from "./FGUI_SelectModePlan";
import FGUI_SelectModeItem from "./FGUI_SelectModeItem";
import FGUI_SelectModeButton from "./FGUI_SelectModeButton";
import FGUI_NewPropertyComp from "./FGUI_NewPropertyComp";
import FGUI_TopResCom2 from "./FGUI_TopResCom2";
import FGUI_skillDesComp from "./FGUI_skillDesComp";
import FGUI_Component17 from "./FGUI_Component17";
import FGUI_HeroUpGradeBtn from "./FGUI_HeroUpGradeBtn";
import FGUI_EverydayDiscountComp from "./FGUI_EverydayDiscountComp";
import FGUI_refreshBtn from "./FGUI_refreshBtn";
import FGUI_CommondityItemBtn from "./FGUI_CommondityItemBtn";
import FGUI_MainResitem from "./FGUI_MainResitem";
import FGUI_Component13 from "./FGUI_Component13";
import FGUI_ComboBox2_popup from "./FGUI_ComboBox2_popup";
import FGUI_ComboBox2 from "./FGUI_ComboBox2";
import FGUI_PGameShop from "./FGUI_PGameShop";
import FGUI_tabBut from "./FGUI_tabBut";
import FGUI_FreeCom from "./FGUI_FreeCom";
import FGUI_PassComp from "./FGUI_PassComp";
import FGUI_Component20 from "./FGUI_Component20";
import FGUI_Button1 from "./FGUI_Button1";
import FGUI_tabBut1 from "./FGUI_tabBut1";
import FGUI_BaseButton from "./FGUI_BaseButton";
import FGUI_TipLabelCom from "./FGUI_TipLabelCom";
import FGUI_BattleLoding from "./FGUI_BattleLoding";
import FGUI_NoviceLoding from "./FGUI_NoviceLoding";
import FGUI_PGameMain from "./FGUI_PGameMain";
import FGUI_PassCardHead from "./FGUI_PassCardHead";
import FGUI_RoundImg from "./FGUI_RoundImg";
import FGUI_BaseView from "./FGUI_BaseView";
import FGUI_BaseUpgradeView from "./FGUI_BaseUpgradeView";
import FGUI_PropertyItem1 from "./FGUI_PropertyItem1";
import FGUI_PropertyItem2 from "./FGUI_PropertyItem2";
import FGUI_PropertyItem3 from "./FGUI_PropertyItem3";
import FGUI_PropertyItem4 from "./FGUI_PropertyItem4";
import FGUI_SelectModelBtn from "./FGUI_SelectModelBtn";
import FGUI_HeadPos from "./FGUI_HeadPos";
import FGUI_HuntBottomComp from "./FGUI_HuntBottomComp";
import FGUI_PGameBox from "./FGUI_PGameBox";
import FGUI_BoxRewardBtn from "./FGUI_BoxRewardBtn";
import FGUI_GameBoxconfirm from "./FGUI_GameBoxconfirm";
import FGUI_PGameSet from "./FGUI_PGameSet";
import FGUI_toggleBtn from "./FGUI_toggleBtn";
import FGUI_lingQuBtn from "./FGUI_lingQuBtn";
import FGUI_PPassCard from "./FGUI_PPassCard";
import FGUI_rodCom from "./FGUI_rodCom";
import FGUI_activePassCardBtn from "./FGUI_activePassCardBtn";
import FGUI_seasonCom from "./FGUI_seasonCom";
import FGUI_PPassCardTop from "./FGUI_PPassCardTop";
import FGUI_PGetReward from "./FGUI_PGetReward";
import FGUI_ray2 from "./FGUI_ray2";
import FGUI_rewardCom2 from "./FGUI_rewardCom2";
import FGUI_chestCom from "./FGUI_chestCom";
import FGUI_getRewardBottomCom from "./FGUI_getRewardBottomCom";
import FGUI_rewardItem from "./FGUI_rewardItem";
import FGUI_PActivePassCard from "./FGUI_PActivePassCard";
import FGUI_passCardVideoBtn from "./FGUI_passCardVideoBtn";
import FGUI_ComboBox3_popup from "./FGUI_ComboBox3_popup";
import FGUI_TipsComp from "./FGUI_TipsComp";
import FGUI_passCardPlusItem from "./FGUI_passCardPlusItem";
import FGUI_GoldTicket1 from "./FGUI_GoldTicket1";
import FGUI_PassBuyLvBtn from "./FGUI_PassBuyLvBtn";

export default class GameMainBinder {
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(FGUI_PGamePause.URL, FGUI_PGamePause);
		fgui.UIObjectFactory.setExtension(FGUI_EnterGameLoadingCom.URL, FGUI_EnterGameLoadingCom);
		fgui.UIObjectFactory.setExtension(FGUI_AniCom.URL, FGUI_AniCom);
		fgui.UIObjectFactory.setExtension(FGUI_ComTips.URL, FGUI_ComTips);
		fgui.UIObjectFactory.setExtension(FGUI_BoosHp_Bar.URL, FGUI_BoosHp_Bar);
		fgui.UIObjectFactory.setExtension(FGUI_passCardUItem.URL, FGUI_passCardUItem);
		fgui.UIObjectFactory.setExtension(FGUI_VirtualRocker.URL, FGUI_VirtualRocker);
		fgui.UIObjectFactory.setExtension(FGUI_yellowkuang.URL, FGUI_yellowkuang);
		fgui.UIObjectFactory.setExtension(FGUI_homeMidItem.URL, FGUI_homeMidItem);
		fgui.UIObjectFactory.setExtension(FGUI_homeTabCom.URL, FGUI_homeTabCom);
		fgui.UIObjectFactory.setExtension(FGUI_PGameCustomsLoading.URL, FGUI_PGameCustomsLoading);
		fgui.UIObjectFactory.setExtension(FGUI_ShareCom.URL, FGUI_ShareCom);
		fgui.UIObjectFactory.setExtension(FGUI_nativeCom.URL, FGUI_nativeCom);
		fgui.UIObjectFactory.setExtension(FGUI_GameFitingPlan.URL, FGUI_GameFitingPlan);
		fgui.UIObjectFactory.setExtension(FGUI_rotatingRay.URL, FGUI_rotatingRay);
		fgui.UIObjectFactory.setExtension(FGUI_playerItem.URL, FGUI_playerItem);
		fgui.UIObjectFactory.setExtension(FGUI_playerCom.URL, FGUI_playerCom);
		fgui.UIObjectFactory.setExtension(FGUI_ConfirmBuy.URL, FGUI_ConfirmBuy);
		fgui.UIObjectFactory.setExtension(FGUI_RoleAdvancedView.URL, FGUI_RoleAdvancedView);
		fgui.UIObjectFactory.setExtension(FGUI_PropItem.URL, FGUI_PropItem);
		fgui.UIObjectFactory.setExtension(FGUI_PGameActive.URL, FGUI_PGameActive);
		fgui.UIObjectFactory.setExtension(FGUI_Component16.URL, FGUI_Component16);
		fgui.UIObjectFactory.setExtension(FGUI_ActiveItem.URL, FGUI_ActiveItem);
		fgui.UIObjectFactory.setExtension(FGUI_ActiveTopCom.URL, FGUI_ActiveTopCom);
		fgui.UIObjectFactory.setExtension(FGUI_DesBtnp.URL, FGUI_DesBtnp);
		fgui.UIObjectFactory.setExtension(FGUI_BlockComp.URL, FGUI_BlockComp);
		fgui.UIObjectFactory.setExtension(FGUI_PGetCard.URL, FGUI_PGetCard);
		fgui.UIObjectFactory.setExtension(FGUI_getCardCom.URL, FGUI_getCardCom);
		fgui.UIObjectFactory.setExtension(FGUI_getCardBoardCom.URL, FGUI_getCardBoardCom);
		fgui.UIObjectFactory.setExtension(FGUI_PConfirm.URL, FGUI_PConfirm);
		fgui.UIObjectFactory.setExtension(FGUI_confirmBoardCom.URL, FGUI_confirmBoardCom);
		fgui.UIObjectFactory.setExtension(FGUI_PGameLoading.URL, FGUI_PGameLoading);
		fgui.UIObjectFactory.setExtension(FGUI_PGamePlay.URL, FGUI_PGamePlay);
		fgui.UIObjectFactory.setExtension(FGUI_PGameStart.URL, FGUI_PGameStart);
		fgui.UIObjectFactory.setExtension(FGUI_FreeReward.URL, FGUI_FreeReward);
		fgui.UIObjectFactory.setExtension(FGUI_FreeRewardItem.URL, FGUI_FreeRewardItem);
		fgui.UIObjectFactory.setExtension(FGUI_FreeRewardBtn.URL, FGUI_FreeRewardBtn);
		fgui.UIObjectFactory.setExtension(FGUI_ModeTipsPlan.URL, FGUI_ModeTipsPlan);
		fgui.UIObjectFactory.setExtension(FGUI_SelectMode.URL, FGUI_SelectMode);
		fgui.UIObjectFactory.setExtension(FGUI_ModeTips.URL, FGUI_ModeTips);
		fgui.UIObjectFactory.setExtension(FGUI_SelectModeItemPlan.URL, FGUI_SelectModeItemPlan);
		fgui.UIObjectFactory.setExtension(FGUI_GameOverPlan.URL, FGUI_GameOverPlan);
		fgui.UIObjectFactory.setExtension(FGUI_UniversalEndPlan.URL, FGUI_UniversalEndPlan);
		fgui.UIObjectFactory.setExtension(FGUI_UniversalTwoEndPlan.URL, FGUI_UniversalTwoEndPlan);
		fgui.UIObjectFactory.setExtension(FGUI_OverEndTaskPlan.URL, FGUI_OverEndTaskPlan);
		fgui.UIObjectFactory.setExtension(FGUI_EndTaskBar.URL, FGUI_EndTaskBar);
		fgui.UIObjectFactory.setExtension(FGUI_EnemyIconPlan.URL, FGUI_EnemyIconPlan);
		fgui.UIObjectFactory.setExtension(FGUI_GameView.URL, FGUI_GameView);
		fgui.UIObjectFactory.setExtension(FGUI_ExistentCom.URL, FGUI_ExistentCom);
		fgui.UIObjectFactory.setExtension(FGUI_bloom.URL, FGUI_bloom);
		fgui.UIObjectFactory.setExtension(FGUI_ButItemOne.URL, FGUI_ButItemOne);
		fgui.UIObjectFactory.setExtension(FGUI_waveRewrds.URL, FGUI_waveRewrds);
		fgui.UIObjectFactory.setExtension(FGUI_UnLockSkin.URL, FGUI_UnLockSkin);
		fgui.UIObjectFactory.setExtension(FGUI_RoleView.URL, FGUI_RoleView);
		fgui.UIObjectFactory.setExtension(FGUI_RoleItem.URL, FGUI_RoleItem);
		fgui.UIObjectFactory.setExtension(FGUI_PropertyItem.URL, FGUI_PropertyItem);
		fgui.UIObjectFactory.setExtension(FGUI_SkillItem.URL, FGUI_SkillItem);
		fgui.UIObjectFactory.setExtension(FGUI_RoleHeadItem.URL, FGUI_RoleHeadItem);
		fgui.UIObjectFactory.setExtension(FGUI_MysteriousRewards.URL, FGUI_MysteriousRewards);
		fgui.UIObjectFactory.setExtension(FGUI_StartView.URL, FGUI_StartView);
		fgui.UIObjectFactory.setExtension(FGUI_BeginButton.URL, FGUI_BeginButton);
		fgui.UIObjectFactory.setExtension(FGUI_EnemyHp_Bar.URL, FGUI_EnemyHp_Bar);
		fgui.UIObjectFactory.setExtension(FGUI_RoleHp_Bar.URL, FGUI_RoleHp_Bar);
		fgui.UIObjectFactory.setExtension(FGUI_PGameEnd.URL, FGUI_PGameEnd);
		fgui.UIObjectFactory.setExtension(FGUI_RoundHalfImg.URL, FGUI_RoundHalfImg);
		fgui.UIObjectFactory.setExtension(FGUI_LightBox.URL, FGUI_LightBox);
		fgui.UIObjectFactory.setExtension(FGUI_D_refreshDiamond.URL, FGUI_D_refreshDiamond);
		fgui.UIObjectFactory.setExtension(FGUI_D_refreshGold.URL, FGUI_D_refreshGold);
		fgui.UIObjectFactory.setExtension(FGUI_GameShopIn.URL, FGUI_GameShopIn);
		fgui.UIObjectFactory.setExtension(FGUI_GameOverRole.URL, FGUI_GameOverRole);
		fgui.UIObjectFactory.setExtension(FGUI_BUFFShow.URL, FGUI_BUFFShow);
		fgui.UIObjectFactory.setExtension(FGUI_BUFFSelect.URL, FGUI_BUFFSelect);
		fgui.UIObjectFactory.setExtension(FGUI_SkillSelect.URL, FGUI_SkillSelect);
		fgui.UIObjectFactory.setExtension(FGUI_BUFFInfo.URL, FGUI_BUFFInfo);
		fgui.UIObjectFactory.setExtension(FGUI_AttackTxT.URL, FGUI_AttackTxT);
		fgui.UIObjectFactory.setExtension(FGUI_ExpTxT.URL, FGUI_ExpTxT);
		fgui.UIObjectFactory.setExtension(FGUI_DiamontemComp.URL, FGUI_DiamontemComp);
		fgui.UIObjectFactory.setExtension(FGUI_CommodityComp.URL, FGUI_CommodityComp);
		fgui.UIObjectFactory.setExtension(FGUI_DiamonItemBtn.URL, FGUI_DiamonItemBtn);
		fgui.UIObjectFactory.setExtension(FGUI_GoldComp.URL, FGUI_GoldComp);
		fgui.UIObjectFactory.setExtension(FGUI_goldItem.URL, FGUI_goldItem);
		fgui.UIObjectFactory.setExtension(FGUI_PGameHome.URL, FGUI_PGameHome);
		fgui.UIObjectFactory.setExtension(FGUI_PGameHunter.URL, FGUI_PGameHunter);
		fgui.UIObjectFactory.setExtension(FGUI_TopItem.URL, FGUI_TopItem);
		fgui.UIObjectFactory.setExtension(FGUI_UnblockSkinBtnp.URL, FGUI_UnblockSkinBtnp);
		fgui.UIObjectFactory.setExtension(FGUI_foreverItem.URL, FGUI_foreverItem);
		fgui.UIObjectFactory.setExtension(FGUI_HunterItem.URL, FGUI_HunterItem);
		fgui.UIObjectFactory.setExtension(FGUI_Elf_Item_pro.URL, FGUI_Elf_Item_pro);
		fgui.UIObjectFactory.setExtension(FGUI_GoldTicket.URL, FGUI_GoldTicket);
		fgui.UIObjectFactory.setExtension(FGUI_SilverTicket.URL, FGUI_SilverTicket);
		fgui.UIObjectFactory.setExtension(FGUI_TicketLight.URL, FGUI_TicketLight);
		fgui.UIObjectFactory.setExtension(FGUI_GetRewardBtn.URL, FGUI_GetRewardBtn);
		fgui.UIObjectFactory.setExtension(FGUI_PassCardListCom.URL, FGUI_PassCardListCom);
		fgui.UIObjectFactory.setExtension(FGUI_passCardFreeItem.URL, FGUI_passCardFreeItem);
		fgui.UIObjectFactory.setExtension(FGUI_SilverTicket1.URL, FGUI_SilverTicket1);
		fgui.UIObjectFactory.setExtension(FGUI_CoTips.URL, FGUI_CoTips);
		fgui.UIObjectFactory.setExtension(FGUI_levelProgressBar.URL, FGUI_levelProgressBar);
		fgui.UIObjectFactory.setExtension(FGUI_experienceBarCom.URL, FGUI_experienceBarCom);
		fgui.UIObjectFactory.setExtension(FGUI_timeCom.URL, FGUI_timeCom);
		fgui.UIObjectFactory.setExtension(FGUI_deadMsgCom.URL, FGUI_deadMsgCom);
		fgui.UIObjectFactory.setExtension(FGUI_hpBar.URL, FGUI_hpBar);
		fgui.UIObjectFactory.setExtension(FGUI_playerHp.URL, FGUI_playerHp);
		fgui.UIObjectFactory.setExtension(FGUI_SkillCom.URL, FGUI_SkillCom);
		fgui.UIObjectFactory.setExtension(FGUI_chooseSkillCom.URL, FGUI_chooseSkillCom);
		fgui.UIObjectFactory.setExtension(FGUI_PHuntTask.URL, FGUI_PHuntTask);
		fgui.UIObjectFactory.setExtension(FGUI_taskProcessingCom.URL, FGUI_taskProcessingCom);
		fgui.UIObjectFactory.setExtension(FGUI_rewardCom.URL, FGUI_rewardCom);
		fgui.UIObjectFactory.setExtension(FGUI_taskItemCom.URL, FGUI_taskItemCom);
		fgui.UIObjectFactory.setExtension(FGUI_taskBtn.URL, FGUI_taskBtn);
		fgui.UIObjectFactory.setExtension(FGUI_taskBtnFinishedCout.URL, FGUI_taskBtnFinishedCout);
		fgui.UIObjectFactory.setExtension(FGUI_huntTaskBoard.URL, FGUI_huntTaskBoard);
		fgui.UIObjectFactory.setExtension(FGUI_adItem.URL, FGUI_adItem);
		fgui.UIObjectFactory.setExtension(FGUI_adProgressBar.URL, FGUI_adProgressBar);
		fgui.UIObjectFactory.setExtension(FGUI_GoonGame.URL, FGUI_GoonGame);
		fgui.UIObjectFactory.setExtension(FGUI_LifeTime30.URL, FGUI_LifeTime30);
		fgui.UIObjectFactory.setExtension(FGUI_Ray.URL, FGUI_Ray);
		fgui.UIObjectFactory.setExtension(FGUI_SetCom.URL, FGUI_SetCom);
		fgui.UIObjectFactory.setExtension(FGUI_HuntBtn.URL, FGUI_HuntBtn);
		fgui.UIObjectFactory.setExtension(FGUI_SelectModePlan.URL, FGUI_SelectModePlan);
		fgui.UIObjectFactory.setExtension(FGUI_SelectModeItem.URL, FGUI_SelectModeItem);
		fgui.UIObjectFactory.setExtension(FGUI_SelectModeButton.URL, FGUI_SelectModeButton);
		fgui.UIObjectFactory.setExtension(FGUI_NewPropertyComp.URL, FGUI_NewPropertyComp);
		fgui.UIObjectFactory.setExtension(FGUI_TopResCom2.URL, FGUI_TopResCom2);
		fgui.UIObjectFactory.setExtension(FGUI_skillDesComp.URL, FGUI_skillDesComp);
		fgui.UIObjectFactory.setExtension(FGUI_Component17.URL, FGUI_Component17);
		fgui.UIObjectFactory.setExtension(FGUI_HeroUpGradeBtn.URL, FGUI_HeroUpGradeBtn);
		fgui.UIObjectFactory.setExtension(FGUI_EverydayDiscountComp.URL, FGUI_EverydayDiscountComp);
		fgui.UIObjectFactory.setExtension(FGUI_refreshBtn.URL, FGUI_refreshBtn);
		fgui.UIObjectFactory.setExtension(FGUI_CommondityItemBtn.URL, FGUI_CommondityItemBtn);
		fgui.UIObjectFactory.setExtension(FGUI_MainResitem.URL, FGUI_MainResitem);
		fgui.UIObjectFactory.setExtension(FGUI_Component13.URL, FGUI_Component13);
		fgui.UIObjectFactory.setExtension(FGUI_ComboBox2_popup.URL, FGUI_ComboBox2_popup);
		fgui.UIObjectFactory.setExtension(FGUI_ComboBox2.URL, FGUI_ComboBox2);
		fgui.UIObjectFactory.setExtension(FGUI_PGameShop.URL, FGUI_PGameShop);
		fgui.UIObjectFactory.setExtension(FGUI_tabBut.URL, FGUI_tabBut);
		fgui.UIObjectFactory.setExtension(FGUI_FreeCom.URL, FGUI_FreeCom);
		fgui.UIObjectFactory.setExtension(FGUI_PassComp.URL, FGUI_PassComp);
		fgui.UIObjectFactory.setExtension(FGUI_Component20.URL, FGUI_Component20);
		fgui.UIObjectFactory.setExtension(FGUI_Button1.URL, FGUI_Button1);
		fgui.UIObjectFactory.setExtension(FGUI_tabBut1.URL, FGUI_tabBut1);
		fgui.UIObjectFactory.setExtension(FGUI_BaseButton.URL, FGUI_BaseButton);
		fgui.UIObjectFactory.setExtension(FGUI_TipLabelCom.URL, FGUI_TipLabelCom);
		fgui.UIObjectFactory.setExtension(FGUI_BattleLoding.URL, FGUI_BattleLoding);
		fgui.UIObjectFactory.setExtension(FGUI_NoviceLoding.URL, FGUI_NoviceLoding);
		fgui.UIObjectFactory.setExtension(FGUI_PGameMain.URL, FGUI_PGameMain);
		fgui.UIObjectFactory.setExtension(FGUI_PassCardHead.URL, FGUI_PassCardHead);
		fgui.UIObjectFactory.setExtension(FGUI_RoundImg.URL, FGUI_RoundImg);
		fgui.UIObjectFactory.setExtension(FGUI_BaseView.URL, FGUI_BaseView);
		fgui.UIObjectFactory.setExtension(FGUI_BaseUpgradeView.URL, FGUI_BaseUpgradeView);
		fgui.UIObjectFactory.setExtension(FGUI_PropertyItem1.URL, FGUI_PropertyItem1);
		fgui.UIObjectFactory.setExtension(FGUI_PropertyItem2.URL, FGUI_PropertyItem2);
		fgui.UIObjectFactory.setExtension(FGUI_PropertyItem3.URL, FGUI_PropertyItem3);
		fgui.UIObjectFactory.setExtension(FGUI_PropertyItem4.URL, FGUI_PropertyItem4);
		fgui.UIObjectFactory.setExtension(FGUI_SelectModelBtn.URL, FGUI_SelectModelBtn);
		fgui.UIObjectFactory.setExtension(FGUI_HeadPos.URL, FGUI_HeadPos);
		fgui.UIObjectFactory.setExtension(FGUI_HuntBottomComp.URL, FGUI_HuntBottomComp);
		fgui.UIObjectFactory.setExtension(FGUI_PGameBox.URL, FGUI_PGameBox);
		fgui.UIObjectFactory.setExtension(FGUI_BoxRewardBtn.URL, FGUI_BoxRewardBtn);
		fgui.UIObjectFactory.setExtension(FGUI_GameBoxconfirm.URL, FGUI_GameBoxconfirm);
		fgui.UIObjectFactory.setExtension(FGUI_PGameSet.URL, FGUI_PGameSet);
		fgui.UIObjectFactory.setExtension(FGUI_toggleBtn.URL, FGUI_toggleBtn);
		fgui.UIObjectFactory.setExtension(FGUI_lingQuBtn.URL, FGUI_lingQuBtn);
		fgui.UIObjectFactory.setExtension(FGUI_PPassCard.URL, FGUI_PPassCard);
		fgui.UIObjectFactory.setExtension(FGUI_rodCom.URL, FGUI_rodCom);
		fgui.UIObjectFactory.setExtension(FGUI_activePassCardBtn.URL, FGUI_activePassCardBtn);
		fgui.UIObjectFactory.setExtension(FGUI_seasonCom.URL, FGUI_seasonCom);
		fgui.UIObjectFactory.setExtension(FGUI_PPassCardTop.URL, FGUI_PPassCardTop);
		fgui.UIObjectFactory.setExtension(FGUI_PGetReward.URL, FGUI_PGetReward);
		fgui.UIObjectFactory.setExtension(FGUI_ray2.URL, FGUI_ray2);
		fgui.UIObjectFactory.setExtension(FGUI_rewardCom2.URL, FGUI_rewardCom2);
		fgui.UIObjectFactory.setExtension(FGUI_chestCom.URL, FGUI_chestCom);
		fgui.UIObjectFactory.setExtension(FGUI_getRewardBottomCom.URL, FGUI_getRewardBottomCom);
		fgui.UIObjectFactory.setExtension(FGUI_rewardItem.URL, FGUI_rewardItem);
		fgui.UIObjectFactory.setExtension(FGUI_PActivePassCard.URL, FGUI_PActivePassCard);
		fgui.UIObjectFactory.setExtension(FGUI_passCardVideoBtn.URL, FGUI_passCardVideoBtn);
		fgui.UIObjectFactory.setExtension(FGUI_ComboBox3_popup.URL, FGUI_ComboBox3_popup);
		fgui.UIObjectFactory.setExtension(FGUI_TipsComp.URL, FGUI_TipsComp);
		fgui.UIObjectFactory.setExtension(FGUI_passCardPlusItem.URL, FGUI_passCardPlusItem);
		fgui.UIObjectFactory.setExtension(FGUI_GoldTicket1.URL, FGUI_GoldTicket1);
		fgui.UIObjectFactory.setExtension(FGUI_PassBuyLvBtn.URL, FGUI_PassBuyLvBtn);
	}
}